package cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-12-01T13:44:36.193-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "SocOrgServiceService", 
//                  wsdlLocation = "http://10.13.25.225:8081/socorg/ooicservices/SocOrgServices?wsdl",
                  wsdlLocation = "http://localhost/ooicservices/SocOrgServices?wsdl",
                  targetNamespace = "http://socialorg.ws.ooic.ru/")
public class SocOrgServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://socialorg.ws.ooic.ru/", "SocOrgServiceService");
    public final static QName SocOrgServicePort = new QName("http://socialorg.ws.ooic.ru/", "SocOrgServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/ooicservices/SocOrgServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SocOrgServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.13.25.225:8081/socorg/ooicservices/SocOrgServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SocOrgServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SocOrgServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SocOrgServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SocOrgServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SocOrgServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SocOrgServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SocOrgService
     */
    @WebEndpoint(name = "SocOrgServicePort")
    public SocOrgService getSocOrgServicePort() {
        return super.getPort(SocOrgServicePort, SocOrgService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SocOrgService
     */
    @WebEndpoint(name = "SocOrgServicePort")
    public SocOrgService getSocOrgServicePort(WebServiceFeature... features) {
        return super.getPort(SocOrgServicePort, SocOrgService.class, features);
    }

}
