package cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-12-01T13:44:36.134-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://socialorg.ws.ooic.ru/", name = "SocOrgService")
@XmlSeeAlso({ObjectFactory.class})
public interface SocOrgService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getOrgBeanListByServGuidRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getOrgBeanListByServGuidResponse")
    @RequestWrapper(localName = "getOrgBeanListByServGuid", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetOrgBeanListByServGuid")
    @WebMethod
    @ResponseWrapper(localName = "getOrgBeanListByServGuidResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetOrgBeanListByServGuidResponse")
    public cxf.client.OrgBeanList getOrgBeanListByServGuid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getLicenseInfByGuidOrgRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getLicenseInfByGuidOrgResponse")
    @RequestWrapper(localName = "getLicenseInfByGuidOrg", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetLicenseInfByGuidOrg")
    @WebMethod
    @ResponseWrapper(localName = "getLicenseInfByGuidOrgResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetLicenseInfByGuidOrgResponse")
    public cxf.client.LicenseBeanList getLicenseInfByGuidOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getSubDivisionBeanListByGuidOrgRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getSubDivisionBeanListByGuidOrgResponse")
    @RequestWrapper(localName = "getSubDivisionBeanListByGuidOrg", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSubDivisionBeanListByGuidOrg")
    @WebMethod
    @ResponseWrapper(localName = "getSubDivisionBeanListByGuidOrgResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSubDivisionBeanListByGuidOrgResponse")
    public cxf.client.SubDivisionBeanList getSubDivisionBeanListByGuidOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getSocOrgListRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getSocOrgListResponse")
    @RequestWrapper(localName = "getSocOrgList", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSocOrgList")
    @WebMethod
    @ResponseWrapper(localName = "getSocOrgListResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSocOrgListResponse")
    public cxf.client.OrgBeanList getSocOrgList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getCheckInfByGuidOrgRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getCheckInfByGuidOrgResponse")
    @RequestWrapper(localName = "getCheckInfByGuidOrg", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetCheckInfByGuidOrg")
    @WebMethod
    @ResponseWrapper(localName = "getCheckInfByGuidOrgResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetCheckInfByGuidOrgResponse")
    public cxf.client.CheckBeanList getCheckInfByGuidOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getSprServiceBeanListRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getSprServiceBeanListResponse")
    @RequestWrapper(localName = "getSprServiceBeanList", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSprServiceBeanList")
    @WebMethod
    @ResponseWrapper(localName = "getSprServiceBeanListResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetSprServiceBeanListResponse")
    public cxf.client.ServiceBeanList getSprServiceBeanList();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getServiceBeanListByGuidDepRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getServiceBeanListByGuidDepResponse")
    @RequestWrapper(localName = "getServiceBeanListByGuidDep", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetServiceBeanListByGuidDep")
    @WebMethod
    @ResponseWrapper(localName = "getServiceBeanListByGuidDepResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetServiceBeanListByGuidDepResponse")
    public cxf.client.ServiceBeanList getServiceBeanListByGuidDep(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getCategoryListRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getCategoryListResponse")
    @RequestWrapper(localName = "getCategoryList", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetCategoryList")
    @WebMethod
    @ResponseWrapper(localName = "getCategoryListResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetCategoryListResponse")
    public cxf.client.CategoryBeanList getCategoryList();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getOrgInfBeanByIdRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getOrgInfBeanByIdResponse")
    @RequestWrapper(localName = "getOrgInfBeanById", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetOrgInfBeanById")
    @WebMethod
    @ResponseWrapper(localName = "getOrgInfBeanByIdResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetOrgInfBeanByIdResponse")
    public cxf.client.OrgInfBean getOrgInfBeanById(
        @WebParam(name = "arg0", targetNamespace = "")
        cxf.client.OrgBean arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getStaffListByGuidDepRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getStaffListByGuidDepResponse")
    @RequestWrapper(localName = "getStaffListByGuidDep", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetStaffListByGuidDep")
    @WebMethod
    @ResponseWrapper(localName = "getStaffListByGuidDepResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetStaffListByGuidDepResponse")
    public cxf.client.StaffBeanList getStaffListByGuidDep(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://socialorg.ws.ooic.ru/SocOrgService/getAreaListRequest", output = "http://socialorg.ws.ooic.ru/SocOrgService/getAreaListResponse")
    @RequestWrapper(localName = "getAreaList", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetAreaList")
    @WebMethod
    @ResponseWrapper(localName = "getAreaListResponse", targetNamespace = "http://socialorg.ws.ooic.ru/", className = "cxf.client.GetAreaListResponse")
    public cxf.client.AreaBeanList getAreaList();
}
